easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Book
        - App\Entity\Author
        - App\Entity\Editor
        - App\Entity\Genre
        - App\Entity\Nationality
